name = "SumTypes"
uuid = "8e1ec7a9-0e02-4297-b0fe-6433085c89f2"
authors = ["MasonProtter <mason.protter@icloud.com>"]
version = "0.1.0"

[deps]
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"

[compat]
MLStyle = "0.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]